name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev/* ]
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make lint

  unit:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: make test-unit

  system:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: make test-system

  docker:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: make test-docker

  server:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: make test-server

  python:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - run: make test-python

  coverage:
    runs-on: ubuntu-latest
    needs: [unit, system, docker, python]
    steps:
    - uses: actions/checkout@v4
    - run: make coverage

  address-sanitizer:
    runs-on: ubuntu-latest
    needs: [unit, system, docker, python]
    steps:
    - uses: actions/checkout@v4
    - run: make asan
