name: Release

on:
  release:
    types: [created]

env:
  TAG: ${{ github.event.release.tag_name }}
  DEPLOYMENT_NAME: ${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  test-aci:
    # needs: ci # TODO: Uncomment when this works to run after regular CI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Log into Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.MANAGED_ID_CLIENT_ID }}
        tenant-id: ${{ secrets.MANAGED_ID_TENANT_ID }}
        subscription-id: ${{ vars.SUBSCRIPTION }}

    - run: make test-aci

  release-docker:
    needs: test-aci
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: make docker
    - run: make test-docker
    - run: make release-docker
