name: Release

on:
  release:
    types: [created]

env:
  TAG: ${{ github.run_id }}-${{ github.run_attempt }} # Use a dummy tag when testing
  DEPLOYMENT_NAME: ${{ github.run_id }}-${{ github.run_attempt }}
  GH_TOKEN: ${{ github.token }}

jobs:
  release-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: make docker
    - run: make test-docker
    - run: TAG=${{ github.event.release.tag_name || 'latest' }} make release-docker
